[package]
name = "renderweave-renderer-layout"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
renderweave-renderer-document = { path = "../document" }
renderweave-renderer-resource = { path = "../resource" }
serde_json.workspace = true

[dev-dependencies]
hex.workspace = true
