[package]
name = "renderweave-renderer-daemon"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
native-text-skia = ["renderweave-renderer-engine/native-text-skia"]

[dependencies]
renderweave-renderer-document = { path = "../document" }
renderweave-renderer-engine = { path = "../engine" }
renderweave-renderer-layout = { path = "../layout" }
renderweave-renderer-protocol = { path = "../protocol" }
renderweave-renderer-resource = { path = "../resource" }

[dev-dependencies]
serde_json.workspace = true
